name: animated_button
description: A simple and highly customizable Animated button with 3D like effect.
version: 0.3.0
homepage: https://github.com/Emadeddin-eibo/animated_button

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter